# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib import util
from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib.models.base_model_ import Model


class AppDelete(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, paas_service_name: str = None):  # noqa: E501
        """AppDelete - a model defined in Swagger

        :param paas_service_name: The paas_service_name of this AppDelete.  # noqa: E501
        :type paas_service_name: str
        """
        self.swagger_types = {"paas_service_name": str}

        self.attribute_map = {"paas_service_name": "paas_service_name"}
        self._paas_service_name = paas_service_name

    @classmethod
    def from_dict(cls, dikt) -> "AppDelete":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The appDelete of this AppDelete.  # noqa: E501
        :rtype: AppDelete
        """
        return util.deserialize_model(dikt, cls)

    @property
    def paas_service_name(self) -> str:
        """Gets the paas_service_name of this AppDelete.


        :return: The paas_service_name of this AppDelete.
        :rtype: str
        """
        return self._paas_service_name

    @paas_service_name.setter
    def paas_service_name(self, paas_service_name: str):
        """Sets the paas_service_name of this AppDelete.


        :param paas_service_name: The paas_service_name of this AppDelete.
        :type paas_service_name: str
        """

        self._paas_service_name = paas_service_name
