# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib import util
from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib.models.base_model_ import Model


class Appdeploy(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, apps: str = None):  # noqa: E501
        """Appdeploy - a model defined in Swagger

        :param apps: The apps of this Appdeploy.  # noqa: E501
        :type apps: str
        """
        self.swagger_types = {"apps": str}

        self.attribute_map = {"apps": "apps"}
        self._apps = apps

    @classmethod
    def from_dict(cls, dikt) -> "Appdeploy":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The appdeploy of this Appdeploy.  # noqa: E501
        :rtype: Appdeploy
        """
        return util.deserialize_model(dikt, cls)

    @property
    def apps(self) -> str:
        """Gets the apps of this Appdeploy.


        :return: The apps of this Appdeploy.
        :rtype: str
        """
        return self._apps

    @apps.setter
    def apps(self, apps: str):
        """Sets the apps of this Appdeploy.


        :param apps: The apps of this Appdeploy.
        :type apps: str
        """

        self._apps = apps
