# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib import util
from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib.models.apps_response_apps import (  # noqa: F401,E501
    AppsResponseApps,
)
from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib.models.base_model_ import Model


class AppsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, apps: List[AppsResponseApps] = None):  # noqa: E501
        """AppsResponse - a model defined in Swagger

        :param apps: The apps of this AppsResponse.  # noqa: E501
        :type apps: List[AppsResponseApps]
        """
        self.swagger_types = {"apps": List[AppsResponseApps]}

        self.attribute_map = {"apps": "apps"}
        self._apps = apps

    @classmethod
    def from_dict(cls, dikt) -> "AppsResponse":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The appsResponse of this AppsResponse.  # noqa: E501
        :rtype: AppsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def apps(self) -> List[AppsResponseApps]:
        """Gets the apps of this AppsResponse.


        :return: The apps of this AppsResponse.
        :rtype: List[AppsResponseApps]
        """
        return self._apps

    @apps.setter
    def apps(self, apps: List[AppsResponseApps]):
        """Sets the apps of this AppsResponse.


        :param apps: The apps of this AppsResponse.
        :type apps: List[AppsResponseApps]
        """

        self._apps = apps
