# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib import util
from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib.models.base_model_ import Model


class AppsResponseApps(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str = None):  # noqa: E501
        """AppsResponseApps - a model defined in Swagger

        :param id: The id of this AppsResponseApps.  # noqa: E501
        :type id: str
        """
        self.swagger_types = {"id": str}

        self.attribute_map = {"id": "id"}
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> "AppsResponseApps":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The appsResponse_apps of this AppsResponseApps.  # noqa: E501
        :rtype: AppsResponseApps
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this AppsResponseApps.


        :return: The id of this AppsResponseApps.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this AppsResponseApps.


        :param id: The id of this AppsResponseApps.
        :type id: str
        """

        self._id = id
