# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib import util
from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib.models.base_model_ import Model


class Appupdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, command: str = None):  # noqa: E501
        """Appupdate - a model defined in Swagger

        :param command: The command of this Appupdate.  # noqa: E501
        :type command: str
        """
        self.swagger_types = {"command": str}

        self.attribute_map = {"command": "command"}
        self._command = command

    @classmethod
    def from_dict(cls, dikt) -> "Appupdate":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The appupdate of this Appupdate.  # noqa: E501
        :rtype: Appupdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def command(self) -> str:
        """Gets the command of this Appupdate.


        :return: The command of this Appupdate.
        :rtype: str
        """
        return self._command

    @command.setter
    def command(self, command: str):
        """Sets the command of this Appupdate.


        :param command: The command of this Appupdate.
        :type command: str
        """

        self._command = command
