# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib import util
from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib.models.base_model_ import Model


class DeployedappsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        nodeid: str = None,
        nodename: str = None,
        paasid: str = None,
        paasname: str = None,
        status: str = None,
        exposedports: List[int] = None,
    ):  # noqa: E501
        """DeployedappsResponse - a model defined in Swagger

        :param nodeid: The nodeid of this DeployedappsResponse.  # noqa: E501
        :type nodeid: str
        :param nodename: The nodename of this DeployedappsResponse.  # noqa: E501
        :type nodename: str
        :param paasid: The paasid of this DeployedappsResponse.  # noqa: E501
        :type paasid: str
        :param paasname: The paasname of this DeployedappsResponse.  # noqa: E501
        :type paasname: str
        :param status: The status of this DeployedappsResponse.  # noqa: E501
        :type status: str
        :param exposedports: The exposedports of this DeployedappsResponse.  # noqa: E501
        :type exposedports: List[int]
        """
        self.swagger_types = {
            "nodeid": str,
            "nodename": str,
            "paasid": str,
            "paasname": str,
            "status": str,
            "exposedports": List[int],
        }

        self.attribute_map = {
            "nodeid": "nodeid",
            "nodename": "nodename",
            "paasid": "paasid",
            "paasname": "paasname",
            "status": "status",
            "exposedports": "exposedports",
        }
        self._nodeid = nodeid
        self._nodename = nodename
        self._paasid = paasid
        self._paasname = paasname
        self._status = status
        self._exposedports = exposedports

    @classmethod
    def from_dict(cls, dikt) -> "DeployedappsResponse":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The deployedappsResponse of this DeployedappsResponse.  # noqa: E501
        :rtype: DeployedappsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nodeid(self) -> str:
        """Gets the nodeid of this DeployedappsResponse.


        :return: The nodeid of this DeployedappsResponse.
        :rtype: str
        """
        return self._nodeid

    @nodeid.setter
    def nodeid(self, nodeid: str):
        """Sets the nodeid of this DeployedappsResponse.


        :param nodeid: The nodeid of this DeployedappsResponse.
        :type nodeid: str
        """

        self._nodeid = nodeid

    @property
    def nodename(self) -> str:
        """Gets the nodename of this DeployedappsResponse.


        :return: The nodename of this DeployedappsResponse.
        :rtype: str
        """
        return self._nodename

    @nodename.setter
    def nodename(self, nodename: str):
        """Sets the nodename of this DeployedappsResponse.


        :param nodename: The nodename of this DeployedappsResponse.
        :type nodename: str
        """

        self._nodename = nodename

    @property
    def paasid(self) -> str:
        """Gets the paasid of this DeployedappsResponse.


        :return: The paasid of this DeployedappsResponse.
        :rtype: str
        """
        return self._paasid

    @paasid.setter
    def paasid(self, paasid: str):
        """Sets the paasid of this DeployedappsResponse.


        :param paasid: The paasid of this DeployedappsResponse.
        :type paasid: str
        """

        self._paasid = paasid

    @property
    def paasname(self) -> str:
        """Gets the paasname of this DeployedappsResponse.


        :return: The paasname of this DeployedappsResponse.
        :rtype: str
        """
        return self._paasname

    @paasname.setter
    def paasname(self, paasname: str):
        """Sets the paasname of this DeployedappsResponse.


        :param paasname: The paasname of this DeployedappsResponse.
        :type paasname: str
        """

        self._paasname = paasname

    @property
    def status(self) -> str:
        """Gets the status of this DeployedappsResponse.


        :return: The status of this DeployedappsResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this DeployedappsResponse.


        :param status: The status of this DeployedappsResponse.
        :type status: str
        """

        self._status = status

    @property
    def exposedports(self) -> List[int]:
        """Gets the exposedports of this DeployedappsResponse.


        :return: The exposedports of this DeployedappsResponse.
        :rtype: List[int]
        """
        return self._exposedports

    @exposedports.setter
    def exposedports(self, exposedports: List[int]):
        """Sets the exposedports of this DeployedappsResponse.


        :param exposedports: The exposedports of this DeployedappsResponse.
        :type exposedports: List[int]
        """

        self._exposedports = exposedports
