# coding: utf-8

from __future__ import absolute_import

from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib import util
from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib.models.base_model_ import Model
from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib.models.edge_cloud_zone import (  # noqa: F401,E501
    EdgeCloudZone,
)


class EdgeCloudZones(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """EdgeCloudZones - a model defined in Swagger"""
        self.swagger_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt) -> "EdgeCloudZones":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EdgeCloudZones of this EdgeCloudZones.  # noqa: E501
        :rtype: EdgeCloudZones
        """
        return util.deserialize_model(dikt, cls)
