# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib import util
from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib.models.base_model_ import Model


class EnvParameterName(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str = None):  # noqa: E501
        """EnvParameterName - a model defined in Swagger

        :param name: The name of this EnvParameterName.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {"name": str}

        self.attribute_map = {"name": "name"}
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> "EnvParameterName":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The env_parameter_name of this EnvParameterName.  # noqa: E501
        :rtype: EnvParameterName
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this EnvParameterName.


        :return: The name of this EnvParameterName.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this EnvParameterName.


        :param name: The name of this EnvParameterName.
        :type name: str
        """

        self._name = name
