# coding: utf-8

from __future__ import absolute_import

from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib import util
from sunrise6g_opensdk.edgecloud.adapters.kubernetes.lib.models.base_model_ import Model


class VolumeMountDeploy(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str = None, storage: str = None):  # noqa: E501
        """VolumeMountDeploy - a model defined in Swagger

        :param name: The name of this VolumeMountDeploy.  # noqa: E501
        :type name: str
        :param storage: The storage of this VolumeMountDeploy.  # noqa: E501
        :type storage: str
        """
        self.swagger_types = {"name": str, "storage": str}

        self.attribute_map = {"name": "name", "storage": "storage"}
        self._name = name
        self._storage = storage

    @classmethod
    def from_dict(cls, dikt) -> "VolumeMountDeploy":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The volume_mount_deploy of this VolumeMountDeploy.  # noqa: E501
        :rtype: VolumeMountDeploy
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this VolumeMountDeploy.


        :return: The name of this VolumeMountDeploy.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this VolumeMountDeploy.


        :param name: The name of this VolumeMountDeploy.
        :type name: str
        """

        self._name = name

    @property
    def storage(self) -> str:
        """Gets the storage of this VolumeMountDeploy.


        :return: The storage of this VolumeMountDeploy.
        :rtype: str
        """
        return self._storage

    @storage.setter
    def storage(self, storage: str):
        """Sets the storage of this VolumeMountDeploy.


        :param storage: The storage of this VolumeMountDeploy.
        :type storage: str
        """

        self._storage = storage
